spring:
  security:
    oauth2:
      client:
        registration:
          sso:
            client-id: sta_atlassian
            client-secret: b8de01ce-9ea2-4f0a-9167-03e5f7908c20
            authorization-grant-type: client_credentials
            scope:
            - bid
        provider:
          sso:
            issuer-uri: https://login.sso.az.run.withtanzu.com
